#!/bin/sh

. ../internal

install() {
  printe "Nothing to install"
}

link() {
  mkdir -p "$HOME"/.local/bin

  for file in "$PWD"/files/*; do
    filename=$(basename "$file")
    prints "Linking script: $filename..."
    ln -sf "$PWD"/files/"$filename" "$HOME"/.local/bin/"$filename"
  done
}

main "$1"
