#!/bin/bash
set -e

main() {
  echo "Installing dependencies: git and make..."
  sudo apt install -y git make

  BASE_DIR="$HOME/workspace/personal"

  mkdir -p "$BASE_DIR"

  REPO_URL="https://github.com/hrvthzslt/mini-dots"
  REPO_DIR="$BASE_DIR/mini-dots"

  if [ -d "$REPO_DIR" ]; then
    echo "Repo already exists. Pulling latest changes..."
    cd "$REPO_DIR"
    git pull
  else
    git clone "$REPO_URL" "$REPO_DIR"
    cd "$REPO_DIR"
  fi

  make setup
}

main
