#!/bin/sh

. ./internal

install() {
  printe "Nothing to install"
}

link() {
  mkdir -p "$HOME"/.local/bin

  for file in "$PWD"/config/scripts/*; do
    filename=$(basename "$file")
    prints "Linking script: $filename..."
    ln -sf "$PWD"/config/scripts/"$filename" "$HOME"/.local/bin/"$filename"
  done
}

main "$1"
