#!/bin/sh

. ./internal

install() {
  prints "Install tools: ctags, man, shellcheck, shfmt..."
  install_package "universal-ctags"
  install_package "man"
  install_package "shellcheck"
  install_package "shfmt"
}

link() {
  printe "Nothing to link."
}

main "$1"
