#!/bin/sh

session() {
  session_name="$(basename "$(pwd)")"
  tmux new -s "$session_name" 2>/dev/null || tmux attach -f "$session_name"
}

se() {
  case "$1" in
    a)
      tmux attach
      ;;
    *)
      session
      ;;
  esac
}

se "$1"
