#!/bin/sh

run_test_environment() {
  rm tags 2>/dev/null
  echo "Starting test container with user/password"
  docker build --build-arg USER_ID="$(id -u)" --build-arg GROUP_ID="$(id -g)" . -t mini-dots:test || exit 1
  docker run -v "$(pwd)"/../:/home/user/mini-dots --hostname computer --rm -it mini-dots:test
}

run_test_environment
