#!/bin/sh

. ../internal

install() {
  install_package "shellcheck"
  install_package "shfmt"
  install_package "gcc"
  install_package "clang-format"
  install_package "pipx"
  prints "Installing ruff..."
  pipx install ruff >/dev/null
}

link() {
  printe "Nothing to link."
}

main "$1"
