#!/bin/sh

. ../internal

install() {
  prints "Install tools: shellcheck, shfmt, gcc and clang-format..."
  install_package "shellcheck"
  install_package "shfmt"
  install_package "gcc"
  install_package "clang-format"
}

link() {
  printe "Nothing to link."
}

main "$1"
