#!/bin/sh

DIR="$(dirname "$(realpath "$0")")"
. "$DIR"/../internal

install() {
  prints "Installing vim..."
  is_debian && sudo apt install -y vim
}

link() {
  prints "Linking vim config..."
  ln -sf "$DIR"/files/.vimrc "$HOME"/.vimrc
}

main "$@"
