#!/bin/sh

. ../internal

install() {
  prints "Installing vim, universal-ctags and man pages..."
  install_package "vim"
  install_package "universal-ctags"
  install_package "man"
}

link() {
  prints "Linking vim config..."
  ln -sf "$PWD"/files/.vimrc "$HOME"/.vimrc
}

main "$1"
